### PR TITLE
Duplicate market fix

### PR DESCRIPTION
**Pull request by maxdebruijn**
Fixed duplicate peers appearing by changing the way they are added.
Peers are now checked on their public key.

### CODE REVIEW

**Comment by hoffmabc** [comment]
Why did you move to pubkey? The GUID is generated from the Pubkey.

**Comment by maxdebruijn** [comment]
GUID can be used too, I thought that the public key would be the safest because that is definitely unique.

**Comment by STRML** [comment]
:+1: LGTM. This could probably be made shorter with a filter, e.g.:

```javascript
$scope.add_peer = function(msg) {
  var exists = angular.filter($scope.peers, function(peer) {
    return peer.pubkey === msg.pubkey;
  });
  if (!exists.length) {
    $scope.peers.push(msg);
  }
}
```

But the effect is the same.

**Comment by Renelvon** [comment]
The reason the build is failing has nothing to do with the changes proposed herein. You can make the PR green just by rebasing on latest `develop`.

**Comment by hoffmabc** [comment]
Please rebase and we can include.

**Comment by Renelvon** [comment]
If this is ready, it can be safely merged. The Travis error is an artifact.

**Pull request merged**
