### PR TITLE
Clean Bitmessage from the Application

### PR DESCRIPTION
**Pull request by hoffmabc**
I've gone through and removed all Bitmessage integration left in the app since we've deprecated it.

### CODE REVIEW

**Comment by hoffmabc** [comment]
Not sure why the dupe commits. Maybe you know @Renelvon ?

**Comment by gubatron** [comment]
maybe the last merge?

(Happy to see this commit :) )

https://www.youtube.com/watch?v=ENOL1RJ1u4s

**Comment by hoffmabc** [comment]
@gubatron @Renelvon ok fixed up the commit issue and it passes pylint so ready for merge whenever it passes Travis.

**Comment by hoffmabc** [comment]
Can I get a review guys? Or do I have to push this myself? @Renelvon @gubatron @cpacia

**Comment by jordonias** [comment]
With a quick glance it looks like the following can be removed:
https://github.com/hoffmabc/OpenBazaar/blob/fix-ico-bug/html/app.js#L38-L41

I'll look it over a bit more when I'm at home.

**Comment by Renelvon** [comment]
Will review today.

**Comment by Renelvon** [comment]
OK, this LGTM, though it doesn't remove the `bitmessage` arguments from the launcher. We can keep it that way for backwards compatibility, but it's better to remove them now than later.

**Comment by Renelvon** [comment]
Let's not drag this PR any longer. I am merging and will submit a PR doing some of the remaining cleanup in the launcher.

**Pull request merged**
