### PR TITLE
Create satoshis filter to fix long prices in contracts table.

### LINKED ISSUE #1303: Long Price in My Contracts View Forces Edit/Remove Buttons offscreen
We should have a high limit on price of a contract and force a text wrap on this field in the GUI so that the buttons don't appear to disappear.

### PR DESCRIPTION
**Pull request by STRML**
Fixes https://www.bountysource.com/issues/15949155-long-price-in-my-contracts-view-forces-edit-remove-buttons-offscreen

Fixes #1303 
imgur

### CODE REVIEW

**Comment by hoffmabc** [comment]
One problem with this I've found so far is that it shows users that the max BTC value is 21,000,000 but yet the underlying value of the contract does not change. It's misleading. I think an additional fix here would be to limit the Modify Contract screen to limit that value so that these are in sync @STRML.

**Comment by STRML** [comment]
That seems fine - I of course chose the 21M value because it is completely nonsensical to have a contract with a value above that. I think this should be rolled into #1307.

**Comment by STRML** [comment]
I've gone ahead and just added a max to the form for now. I think this is a good interim fix until we add the display preference.

**Comment by STRML** [comment]
@hoffmabc Do you want to go ahead with this solution or the other one? If we go with this, we can roll the display preferences into the satoshis filter.

**Comment by hoffmabc** [comment]
Let's go with this one.

**Comment by hoffmabc** [comment]
Let's merge as is and we can improve in the next round.

**Comment by hoffmabc** [comment]
@STRML claim your bounty on bountysource so I can close it.

**Comment by STRML** [comment]
Alright. Just did

**Pull request merged**
