### PR TITLE
Settings ui revisions

### PR DESCRIPTION
**Pull request by Klakurka**
Moved some inline CSS into stylesheet and swapped out checkbox in fav our of bootstrap's button group in Settings pages.

arbiter

notary

advanced

### CODE REVIEW

**Comment by hoffmabc** [comment]
I like the switch for yes/no button groups.

**Comment by Renelvon2** [comment]
@hoffmabc, per the email I sent to you, could you add this account to the project temporarily as I've lost access to the other one.

**Comment by hoffmabc** [comment]
Ok revoked the other and added this one.

**Comment by Renelvon2** [comment]
@hoffmabc, I can see you've removed the other one, but I don't think you've added this one.

**Comment by hoffmabc** [comment]
screen shot 2015-01-02 at 12 37 59 pm

**Comment by Renelvon2** [comment]
Thanks.

**Pull request merged**
