### PR TITLE
Monthly dependency check and upgrade

### PR DESCRIPTION
**Pull request by Renelvon**
### Changelog:
* Upgraded *most* dependencies to latest available editions. See commits for specific information about each package.
* Kept back `requests`, `tornado` and `Twisted` as the new APIs are possibly backwards-incompatible and need more thorough checking.
* Kept back `pyelliptic`. It upgrades from a SHA1 to SHA256 signatures, which, while being an excellent move, splits the network. We need to think about that more.
* Fixed a couple of `pylint` warnings.

### CODE REVIEW

**Comment by Renelvon** [comment]
Travis failure!

Probably the new SHA256 signing scheme of pyelliptic is not a good idea right now. If not everybody updates, it will cause a network split. I am removing that commit.

**Comment by hoffmabc** [comment]
Ok sounds good

**Comment by hoffmabc** [comment]
Please rebase @Renelvon

**Comment by gubatron** [comment]
:+1:

**Comment by hoffmabc** [comment]
Anyone home @Renelvon?

**Pull request merged**
