### PR TITLE
Image preview

### PR DESCRIPTION
**Pull request by drwasho**
**Image Preview**
When an image URL is pasted into the input box, the image will be immediately displayed below.

**Separate Keyword Section**
Some users have complained that the *keyword* section was difficult to find. I moved it below the image area.

This is what it looks like:

image

### CODE REVIEW

**Comment by hoffmabc** [comment]
I like the sentiment but not sure I like the presentation. I'd like some thoughts from the design guys on this one.

**Comment by drwasho** [comment]
I tried aligning the image in the center but ran into problems... would appreciate some help here (my usual `margin-left: auto; margin-right: auto` trick didn't work.

Also, given that functionally it does it is supposed to do, can we merge the PR and make any necessary presentation changes as a follow-up?

**Comment by hoffmabc** [comment]
I'm going to NACK this one. I think the keywords addition makes it a no go. The image preview is good and I would approve that alone but not with this rider included. It needs more thought. If you can revert that other commit then I will merge the image fix.

**Comment by hoffmabc** [comment]
It might be better to just do a clean PR with only one commit including the image tweak. Do you mind redoing this one? There's 4 commits to do one thing.

**Comment by hoffmabc** [comment]
Sorry!

**Pull request closed without merging**
