### PR TITLE
Fix path to pysqlcipher to one that exists. Still will not work until be...

### PR DESCRIPTION
**Pull request by sammiejenkins**
...low pull request is merged. Until then will have to manually download and make same change in pull request and then point configure.ps1 at local changed zip file instead of remote path.

https://github.com/leapcode/pysqlcipher/pull/14

### CODE REVIEW

**Comment by yagoulas** [comment]
I think it is better to change requirements.txt to install the latest version so we can get rid once and for all, all pysqlcipher hacks from configure.ps1.

**Comment by hoffmabc** [comment]
:+1:

**Comment by Renelvon** [comment]
Who-hoo! The `pysqlcipher` team finally [upgraded](https://pypi.python.org/pypi/pysqlcipher) the version @ pypi!

Please rebase the PR on latest `develop`.

**Comment by yagoulas** [comment]
Hello sammiejenkins, sorry for the delay. Really thanks for taking care of this. This is a bit bureaucratic but my opinion is that we should fix this with two separate PRs. The idea is that updating pysqlcipher affects the whole project on every platform and this can cause every short of problems. This is also a security improvement as with the newer version, it is installed in a more secure way. So let me create a new PR that will update pysqlcipher and after that, you will squash your commits and rebase on my commit. It would also be great if you removed every hack for pysqlcipher from configure.ps1 as the change in requirements.txt should fix all the problems we have with it for windows one and for all.

**Comment by hoffmabc** [comment]
Updates?

**Comment by drwasho** [comment]
Should we close this now that we've dumped pysqlcipher?

**Pull request closed without merging**
