### PR TITLE
Fix 404 image messages in console.log

### LINKED ISSUE #1224: 404 error log
tornado.access - WARNING - 404 GET /html/%7B%7Bmyself.settings.avatar_url%7D%7D (127.0.0.1) 1.22ms
tornado.access - WARNING - 404 GET /html/%7B%7Bpeer.avatar_url%7D%7D (127.0.0.1) 1.22ms
tornado.access - WARNING - 404 GET /html/%7B%7Bshout.avatar_url%7D%7D (127.0.0.1) 1.21ms

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11282176-404-error-log?utm_campaign=plugin&utm_content=tracker%2F1516753&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1516753&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hoffmabc**
Fixes #1224

### CODE REVIEW

**Comment by hoffmabc** [comment]
@STRML do you mind reviewing this short PR?

**Comment by STRML** [comment]
No problem. Can take a look tonight, moving apartments right now.

**Comment by hoffmabc** [comment]
Thanks!

**Comment by STRML** [comment]
Cool. Looks good. The `data-` prefix is actually optional and only needed if you really want it to pass HTML validators, which is not really necessary IMO. But the first few edits look like the fixed the issue.

**Comment by hoffmabc** [comment]
Just trying to be consistent. Thanks.

**Pull request merged**
