### PR TITLE
Minor: changed `./configure` message

### PR DESCRIPTION
**Pull request by amingilani**
I started with fixing a typo, wound up changing the whole message. Already tested, but it's always nice to have another LGTM. Lemme know if you want a squash. :smile:

The ending configure message now outputs:
```
   ____                     ____                            
  / __ \                   |  _ \                           
 | |  | |_ __   ___ _ __   | |_) | __ _ ______ _  __ _ _ __ 
 | |  | |  _ \ / _ \  _ \  |  _ < / _` |_  / _` |/ _` |  __|
 | |__| | |_) |  __/ | | | | |_) | (_| |/ / (_| | (_| | |   
  \____/| .__/ \___|_| |_| |____/ \__,_/___\__,_|\__,_|_|   
        | |                                                 
        |_|                                                 

                                                    Beta 3.0


OpenBazaar configuration finished!
Run './openbazaar start; tail -F logs/production.log' to start OpenBazaar and output logs.
```

### CODE REVIEW

**Comment by abderraouf-adjal** [comment]
It will be better code if it print the version dynamically. I mean it must get the version from a file that contains the version.
If the code merged, the devs have to change the version manually every time in the ASCII art.

**Comment by amingilani** [comment]
Yes, that hit me right before I fell asleep last night, lol. Okay, here. It uses `awk` and parses the version from the `changelog`. It now says:

```
   ____                     ____                            
  / __ \                   |  _ \                           
 | |  | |_ __   ___ _ __   | |_) | __ _ ______ _  __ _ _ __ 
 | |  | |  _ \ / _ \  _ \  |  _ < / _` |_  / _` |/ _` |  __|
 | |__| | |_) |  __/ | | | | |_) | (_| |/ / (_| | (_| | |   
  \____/| .__/ \___|_| |_| |____/ \__,_/___\__,_|\__,_|_|   
        | |                                                 
        |_|                                                 

                                              Release (0.3.1)


OpenBazaar configuration finished!
Run './openbazaar start; tail -F logs/production.log' to start OpenBazaar and output logs.
```

I literally had to learn basic awk right now. @abderraouf-adjal could you please look this over?

**Comment by abderraouf-adjal** [comment]
@amingilani check your shell code in http://www.shellcheck.net

**Comment by amingilani** [comment]
@abderraouf-adjal, thanks for that. The `awk` expression works, but I placed the expression inside double quotes. Tested it, too.

**Comment by amingilani** [comment]
This pull request has been squashed and is ready to be merged.

This commit changes the output of the current `doneMessage` to:
```
   ____                     ____                            
  / __ \                   |  _ \                           
 | |  | |_ __   ___ _ __   | |_) | __ _ ______ _  __ _ _ __ 
 | |  | |  _ \ / _ \  _ \  |  _ < / _` |_  / _` |/ _` |  __|
 | |__| | |_) |  __/ | | | | |_) | (_| |/ / (_| | (_| | |   
  \____/| .__/ \___|_| |_| |____/ \__,_/___\__,_|\__,_|_|   
        | |                                                 
        |_|                                                 

                                             Release (0.3.1)


OpenBazaar configuration finished!
Run './openbazaar start; tail -F logs/production.log' to start OpenBazaar and output logs.
```

Where the Release version is dynamically parsed from the `changelog`. I started by fixing a typo in the output, and ended up changing the whole thing.

**Pull request merged**
