### PR TITLE
Add Euro value and UI Fix for new contracts

### LINKED ISSUE #1239: Price input is unclear and confusing users
The price input section in contracts shows a dollar sign in order to help convert, but it makes uses think they are inputting the price in USD.

priceob

 I've already seen multiple examples of users putting the price in USD instead of Bitcoin. The interface should be changed to make it more clear the price is set in Bitcoin, and the USD is only there as a conversion tool.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11805066-price-input-is-unclear-and-confusing-users?utm_campaign=plugin&utm_content=tracker%2F1516753&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1516753&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hoffmabc**
Current UI for Adding Contracts is confusing for price. This should clear it up.

Fixes #1239

### CODE REVIEW

**Comment by hoffmabc** [comment]
Now looks like this.

screen shot 2015-04-26 at 9 25 43 am

**Comment by drwasho** [comment]
http://www.reactiongifs.com/r/kfp.gif

**Comment by drwasho** [comment]
Reviewed the code, looks good. Happy to merge once it passes Travis.

**Comment by hoffmabc** [comment]
Alrighty. Looks good.

**Pull request merged**
