### PR TITLE
Included license summary in Readme

### PR DESCRIPTION
**Pull request by benhc123**
See "files changed"

### CODE REVIEW

**Comment by dionyziz** [comment]
I don't think it's necessary to include the full license in the readme file. That's why the license file is for.

**Comment by benhc123** [comment]
@dionyziz, It doesn't really take anything away from the Readme or License file though.

**Comment by dionyziz** [comment]
@benhc123 It's just information duplication. It makes the README file unnecessarily long, while this information can easily be linked-to. That's the same reason we don't include the full CONTRIBUTING text in README – keeping things short is a virtue, especially when it comes to the first page a user will ever see when looking at this project. I think we don't want it to be overwhelming.

**Comment by benhc123** [comment]
Fair Point. Thanks for reply.

**Pull request closed without merging**
