### PR TITLE
Update README.md for uninstall issue

### PR DESCRIPTION
**Pull request by ABISprotocol**
Credit to @SamPatt for this solution.

### CODE REVIEW

**Comment by ABISprotocol** [comment]
Well, I really don't get why my checks on this keep failing.  Wondering if someone else - @SamPatt - can just lift the text proposed from this and do a commit / pull request..

**Comment by cgruber** [comment]
If the build is currently already failing, then your build would fail. Updating the readme seems like it could not affect the build in the way it's currently failing, which is some python module loading that's gone haywire in the test classes.

**Comment by ABISprotocol** [comment]
Yes, completely haywire. I just don't understand why it would do this and want to dig into it more but am about to start doing laundry for a trip to see family, so...

**Comment by hoffmabc** [comment]
Looks good.

**Comment by ABISprotocol** [comment]
@hoffmabc TY

**Pull request merged**
