### PR TITLE
wrap long prices

### LINKED ISSUE #1303: Long Price in My Contracts View Forces Edit/Remove Buttons offscreen
We should have a high limit on price of a contract and force a text wrap on this field in the GUI so that the buttons don't appear to disappear.

### PR DESCRIPTION
**Pull request by Idealist42**
fix for long contract prices pushing buttons off screen.

Fixes #1303

### CODE REVIEW

**Comment by Idealist42** [comment]
Should the fix I came up with be applied to other <td> tags as well?  Also, it would make sense to limit the length of the price.  It would be impossible for a bitcoin price to have more than 16 digits.

**Comment by hoffmabc** [comment]
Looks like we have two proposed solutions to this wrapping issue so I will review tonight.

**Comment by hoffmabc** [comment]
Reference #1304

**Comment by gubatron** [comment]
@Idealist42 can you include a screenshot with an example of how the wrapped amount looks like?

Other things to consider:
- Settings > Default Bitcoin Unit > [ BTC, mBTC, uBTC ]
- The use of ellipsis to avoid wrapping, if you do want to see the full amount, you could click to see the full amount, which could or could not end up wrapped depending on where it's displayed, thus keeping the look of say, a table, uniform in row height.

**Comment by Idealist42** [comment]
Sure.  As soon as I get home.  Flying from New York to Seattle right now.

It seems like it might be better to limit the number of digits to 16, since that's the most a valid amount of Bitcoin could possibly have.

**Comment by Idealist42** [comment]
screenshot of long price wrapped...

**Comment by hoffmabc** [comment]
This should wrap the Shipping Price as well. It still has issues as in the screenshot below. I am beginning to think the best option is to fix the Add/Modify Contract screen to validate the BTC input for the Price and Shipping Price.

screen shot 2015-05-21 at 2 38 32 pm

**Comment by hoffmabc** [comment]
@gubatron I think the default value of BTC is a good feature but outside the scope of this issue. I will open an additional one.

**Comment by gubatron** [comment]
thanks for posting that screenshot, a price like that shouldn't take more than one line and should probably be expandable.

Also, does Bitcoin even allow for such amount when you can only have 21million btcs?

**Comment by hoffmabc** [comment]
I think the first comment @gubatron is moot because the amount is invalid and this should never be an issue to begin with. The input form needs to be validated to that effect.

**Comment by hoffmabc** [comment]
Not sure why this was closed.

**Comment by Idealist42** [comment]
I added some simple angular front end validation to the form inputs and removed the previous code for wrapping the text.

**Comment by hoffmabc** [comment]
@Idealist42 can we combine this with @STRML's proposal? I will award the bounty to both of you so that's not an issue, but I would like to bring the best of both of these into one. Thoughts guys?

**Comment by hoffmabc** [comment]
Re: #1304

**Comment by Idealist42** [comment]
sounds good.

**Comment by STRML** [comment]
No need to merge them - #1304 already has a max on the number fields, but the unrelated fix to `remote_images.push($scope.contract.remoteImages[1]);` and `[2]` should be also be committed, perhaps seperately.

**Comment by abderraouf-adjal** [comment]
| Bitcoin even allow for such amount when you can only have 21million btcs?
+1 @gubatron 

And no way to sell a product with price more than (21,000,000)/2=10,500,000

**Comment by hoffmabc** [comment]
@Idealist42 I'm going to close this issue but would like to bounty you for your work. Please provide me a BTC address here or @ brian@openbazaar.org so I can send it.

**Pull request closed without merging**
